on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      cache_url:
        description: 'Point to the URL of your simple upload server'
        required: true
        type: string
        default: ''
      cache_token:
        description: 'Token for authentication with your simple upload server'
        required: true
        type: string
        default: ''
jobs:
  create_cached_element:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo as a base for testing
        run: git clone https://github.com/joernott/localcache --branch master --single-branch testfolder

      - name: Cache current installation
        uses: ./localcache
        with:
          path: |
            ./testfolder
          key: testfolder-${{ github.run_number }}-${{ github.run_attempt }}
          cache_url: ${{ inputs.cache_url }}
          cache_token: ${{ inputs.cache_token }}
  restore_cached_element:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached folder
        uses: ./localcache
        with:
          path: |
            ./testfolder
          key: testfolder-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            testfolder-${{ github.run_number }}-${{ github.run_attempt }}
          cache_url: ${{ inputs.cache_url }}
          cache_token: ${{ inputs.cache_token }}
      - name: Show folder content
        run: |
          find .